### PR TITLE
build: fix icu support when target arch != host

### PR DESCRIPTION
**Pull request by misterdjules**
Without this change, I get the following error when running configure with `--dest-cpu=ia32` on a x64 system:

```
➜  node git:(srl-v0.12-autoicu) ✗ ./configure --dest-cpu=ia32 --with-intl=small-icu
creating  ./icu_config.gypi
* Using ICU in ./deps/icu
creating  ./icu_config.gypi
{ 'target_defaults': { 'cflags': [],
                       'default_configuration': 'Release',
                       'defines': ['OPENSSL_NO_SSL2=1'],
                       'include_dirs': [],
                       'libraries': []},
  'variables': { 'clang': 1,
                 'host_arch': 'x64',
                 'icu_data_file': 'icudt54l.dat',
                 'icu_data_in': '../../deps/icu/source/data/in/icudt54l.dat',
                 'icu_endianness': 'l',
                 'icu_gyp_path': 'tools/icu/icu-generic.gyp',
                 'icu_path': './deps/icu',
                 'icu_small': 'true',
                 'icu_ver_major': '54',
                 'node_install_npm': 'true',
                 'node_prefix': '',
                 'node_shared_cares': 'false',
                 'node_shared_http_parser': 'false',
                 'node_shared_libuv': 'false',
                 'node_shared_openssl': 'false',
                 'node_shared_v8': 'false',
                 'node_shared_zlib': 'false',
                 'node_tag': '',
                 'node_use_dtrace': 'true',
                 'node_use_etw': 'false',
                 'node_use_mdb': 'false',
                 'node_use_openssl': 'true',
                 'node_use_perfctr': 'false',
                 'openssl_no_asm': 0,
                 'python': '/usr/bin/python',
                 'target_arch': 'ia32',
                 'uv_library': 'static_library',
                 'uv_parent_path': '/deps/uv/',
                 'uv_use_dtrace': 'true',
                 'v8_enable_gdbjit': 0,
                 'v8_enable_i18n_support': 1,
                 'v8_no_strict_aliasing': 1,
                 'v8_optimized_debug': 0,
                 'v8_random_seed': 0,
                 'v8_use_snapshot': 'true',
                 'want_separate_host_toolset': 1}}
creating  ./config.gypi
creating  ./config.mk
gyp: Dependency '/Users/JulienGilli/dev/node/tools/icu/icu-generic.gyp:icuuc#target' not found while trying to load target /Users/JulienGilli/dev/node/deps/v8/tools/gyp/v8.gyp:v8_base#target
Error running GYP
➜  node git:(srl-v0.12-autoicu) ✗
```

The change in this PR fixes it, but I'm not sure it's the proper way to do it.

### CODE REVIEW

**Comment by misterdjules** [comment]
I haven't tested cross compiling for ia32 on a x64 host on Windows, and I haven't tested cross-compiling for x64 on a ia32 host on any system.

The only cross-compilation configurations I have tested so far are target == ia32 && host == x64 on MacOS X and Linux.

I'll keep you posted when I have some time to test more configurations.

**Comment by srl295** [comment]
@misterdjules first, thanks for the report and creating the PR.  I don't think it can fix exactly that way, but I will take a look.

**Comment by srl295** [comment]
@misterdjules I really don't understand this or why your patch 'fixes' it. `icu-generic.gyp:icuuc#target' not found` is the error, but you fixed it by adding `#host`. @bnoordhuis any ideas?

**Comment by srl295** [comment]
Also I note that `--dest-cpu=ia32` also builds the `host` tools with `i386`.

**Comment by misterdjules** [comment]
@srl295 Indeed, the error message doesn't make sense to me too, and if I rerun the configure command within your branch, I get the error message that I would expect:

```
  node git:(dc2100e) ✗ ./configure --dest-cpu=ia32 --with-intl=small-icu    
creating  ./icu_config.gypi
* Using ICU in ./deps/icu
creating  ./icu_config.gypi
{ 'target_defaults': { 'cflags': [],
                       'default_configuration': 'Release',
                       'defines': ['OPENSSL_NO_SSL2=1'],
                       'include_dirs': [],
                       'libraries': []},
  'variables': { 'clang': 1,
                 'host_arch': 'x64',
                 'icu_data_file': 'icudt54l.dat',
                 'icu_data_in': '../../deps/icu/source/data/in/icudt54l.dat',
                 'icu_endianness': 'l',
                 'icu_gyp_path': 'tools/icu/icu-generic.gyp',
                 'icu_path': './deps/icu',
                 'icu_small': 'true',
                 'icu_ver_major': '54',
                 'node_install_npm': 'true',
                 'node_prefix': '',
                 'node_shared_cares': 'false',
                 'node_shared_http_parser': 'false',
                 'node_shared_libuv': 'false',
                 'node_shared_openssl': 'false',
                 'node_shared_v8': 'false',
                 'node_shared_zlib': 'false',
                 'node_tag': '',
                 'node_use_dtrace': 'true',
                 'node_use_etw': 'false',
                 'node_use_mdb': 'false',
                 'node_use_openssl': 'true',
                 'node_use_perfctr': 'false',
                 'openssl_no_asm': 0,
                 'python': '/usr/bin/python',
                 'target_arch': 'ia32',
                 'uv_library': 'static_library',
                 'uv_parent_path': '/deps/uv/',
                 'uv_use_dtrace': 'true',
                 'v8_enable_gdbjit': 0,
                 'v8_enable_i18n_support': 1,
                 'v8_no_strict_aliasing': 1,
                 'v8_optimized_debug': 0,
                 'v8_random_seed': 0,
                 'v8_use_snapshot': 'true',
                 'want_separate_host_toolset': 1}}
creating  ./config.gypi
creating  ./config.mk
gyp: Dependency '/Users/JulienGilli/dev/node/tools/icu/icu-generic.gyp:icui18n#host' not found while trying to load target /Users/JulienGilli/dev/node/deps/v8/tools/gyp/v8.gyp:v8_base#host
Error running GYP
➜  node git:(dc2100e) ✗
```

I don't know why I got the error message that mentions `#target` in the first place. It is possible that I had some local modifications when I copy/pasted the error message, or that I copy/pasted the wrong error message.

Did you run this command on your machine? If so, what error message do you get?

**Comment by srl295** [comment]
@misterdjules yes I get the same message. I set up a new branch https://github.com/srl295/node/tree/srl-v0.12-FixToolsetAgain for just this, and reverted my `srl-v0.12-autoicu` branch to not have any fixes for this issue #12

**Comment by srl295** [comment]
also see https://github.com/joyent/node/issues/7676#issuecomment-60474308 for the previous `toolset` issues. _edit_ @misterdjules your PR unfortunately brings back these errors:

```
tools/icu/icudata.target.mk:26: warning: overriding commands for target `/Users/srl/src/node/out/Release/obj/gen/icudt54l.dat'
tools/icu/icudata.host.mk:26: warning: ignoring old commands for target `/Users/srl/src/node/out/Release/obj/gen/icudt54l.dat'
tools/icu/icudata.target.mk:52: warning: overriding commands for target `/Users/srl/src/node/out/Release/obj/gen/icudt54.dat'
tools/icu/icudata.host.mk:52: warning: ignoring old commands for target `/Users/srl/src/node/out/Release/obj/gen/icudt54.dat'
tools/icu/icudata.target.mk:78: warning: overriding commands for target `/Users/srl/src/node/out/Release/obj/gen/icudt54_dat.c'
tools/icu/icudata.host.mk:78: warning: ignoring old commands for target `/Users/srl/src/node/out/Release/obj/gen/icudt54_dat.c'
```

**Pull request closed without merging**
